ceph-windows: Use vstart cluster for Ceph Windows tests
Previously, we spawned a minimal cluster with `cephadm` just to have
a Ceph API available (without any OSDs configured).

New Ceph Windows tests will be available that require actual Ceph
store, so a fully functional Ceph cluster is needed.

The entire ceph-windows testing is done with libvirt VMs now.
This way, we avoid accidentally tainting the CI machines after
each job run.

Building and running Ceph vstart doesn't drastically impact the job
running times, since the CI machines have a lot of CPU cores available.

Signed-off-by: Ionut Balutoiu <ibalutoiu@cloudbasesolutions.com>

diff --git a/scripts/ceph-windows/run_tests b/scripts/ceph-windows/run_tests
--- a/scripts/ceph-windows/run_tests
+++ b/scripts/ceph-windows/run_tests
@@ -2,52 +2,17 @@
 set -o errexit
 set -o pipefail
 
-if [[ ! -f $WORKSPACE/ceph.zip ]]; then
-    echo "ERROR: The Ceph Windows build zip file doesn't exist at $WORKSPACE/ceph.zip"
-    exit 1
-fi
+if [[ ! -f $WORKSPACE/ceph.zip ]]; then echo "ERROR: The Ceph Windows build zip file doesn't exist at '$WORKSPACE/ceph.zip'"; exit 1; fi
+if [[ ! -f $CEPH_WINDOWS_CONF ]]; then echo "ERROR: The Ceph Windows config file doesn't exist at '$CEPH_WINDOWS_CONF'"; exit 1; fi
+if [[ ! -f $CEPH_KEYRING ]]; then echo "ERROR: The Ceph keyring file doesn't exist at '$CEPH_KEYRING'"; exit 1; fi
 
-CEPHADM_RELEASE=${CEPHADM_RELEASE:-"quincy"}
+if [[ -z $WINDOWS_SSH_USER ]]; then echo "ERROR: The WINDOWS_SSH_USER env variable is not set"; exit 1; fi
+if [[ -z $WINDOWS_VM_IP ]]; then echo "ERROR: The WINDOWS_VM_IP env variable is not set"; exit 1; fi
+
+export SSH_USER=$WINDOWS_SSH_USER
+export SSH_ADDRESS=$WINDOWS_VM_IP
+
 WIN_USERSPACE_CRASH_DUMPS=${WIN_USERSPACE_CRASH_DUMPS:-"C:\\userspace_crash_dumps"}
-
-#
-# Install requirements (if needed)
-#
-if ! sudo docker version &>/dev/null; then
-    sudo apt-get update
-    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
-
-    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
-    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-
-    sudo apt-get update
-    sudo apt-get install -y docker-ce docker-ce-cli containerd.io
-
-    sudo usermod -aG docker $USER
-fi
-if ! which xmllint >/dev/null; then
-    sudo apt-get update
-    sudo apt-get install -y libxml2-utils
-fi
-
-#
-# Start minimal Ceph development cluster via cephadm
-#
-curl -L "https://github.com/ceph/ceph/raw/${CEPHADM_RELEASE}/src/cephadm/cephadm" -o $WORKSPACE/cephadm
-chmod +x $WORKSPACE/cephadm
-sudo virsh net-dumpxml default > $WORKSPACE/default-net.xml
-MON_IP=`xmllint --xpath 'string(/network/ip/@address)' $WORKSPACE/default-net.xml`
-sudo rm $WORKSPACE/default-net.xml
-sudo $WORKSPACE/cephadm bootstrap --allow-fqdn-hostname --single-host-defaults --mon-ip $MON_IP
-HOST_DISTRO=$(lsb_release -cs)
-curl -s -L https://shaman.ceph.com/api/repos/ceph/main/latest/ubuntu/$HOST_DISTRO/flavors/default/repo?arch=$(arch) | sudo tee /etc/apt/sources.list.d/ceph.list
-sudo $WORKSPACE/cephadm install ceph-common
-
-sudo cp /etc/ceph/ceph.conf $WORKSPACE/ceph.conf
-sudo cp /etc/ceph/ceph.client.admin.keyring $WORKSPACE/keyring
-sudo chown $USER $WORKSPACE/ceph.conf $WORKSPACE/keyring
-
-sudo ceph osd pool create rbd
 
 #
 # Clone ceph-win32-tests repo
@@ -63,8 +28,8 @@ ssh_exec powershell.exe /workspace/repos/ceph-win32-tests/test_host/set_userspac
 # Copy the ceph.conf and keyring to the Windows VM
 #
 ssh_exec powershell.exe mkdir -force /ProgramData/ceph/out
-scp_upload $WORKSPACE/ceph.conf /ProgramData/ceph/ceph.conf
-scp_upload $WORKSPACE/keyring /ProgramData/ceph/keyring
+scp_upload $CEPH_WINDOWS_CONF /ProgramData/ceph/ceph.conf
+scp_upload $CEPH_KEYRING /ProgramData/ceph/keyring
 
 #
 # Setup the Ceph Windows build in the Windows VM
