prevent an early exit from a non-zero exit status
Signed-off-by: Alfredo Deza <adeza@redhat.com>

diff --git a/ceph-build-next/build/build_deb b/ceph-build-next/build/build_deb
--- a/ceph-build-next/build/build_deb
+++ b/ceph-build-next/build/build_deb
@@ -36,7 +36,8 @@ vers=`cat ./dist/version`
 distro=`python -c "exec 'import platform; print platform.linux_distribution()[0].lower()'"`
 chacra_endpoint="ceph/${chacra_ref}/${distro}/${DIST}/${ARCH}"
 
-chacractl exists binaries/${chacra_endpoint}; exists=$? || true
+# prevent early exit from a non-zero exit because we use `set -e`
+! chacractl exists binaries/${chacra_endpoint}; exists=$? || true
 
 # if the binary already exists in chacra, do not rebuild
 if [ $exists -eq 0 ] && [ "$FORCE" = false ] ; then
